name = "clicko-static"
compatibility_date = "2024-01-01"

# Pages configuration
[env.production]
name = "clicko-static"

# Environment variables for Resend API
[env.production.vars]
RESEND_API_KEY = "re_ciFGGhwD_EWw3w69J6XxPMCfkoW7BLWkC"

# Functions configuration
[functions]
# Functions will be automatically detected in the functions/ directory
